### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by harry-chin** [open-xml-templating/pizzip#10]
Recently I found that DeprecationWarning is happening while using this library.
Full error message is as follows:

[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Refer to nodeBuffer.js

`module.exports = function(data, encoding) {
	return new Buffer(data, encoding);
};`

**Comment by edi9999** [comment]
Hello, please propose a pull request for that, I don't have much time right now and won't be available any time soon.

**Comment by edi9999** [comment]
This is fixed since version 3.1.1 which I 've just released
