### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/pako.es5.js'

### ISSUE THREAD

**Issue by velislavgerov** [open-xml-templating/pizzip#18]
Hello there, @edi9999,

I noticed that [this change](https://github.com/open-xml-templating/pizzip/commit/d3cdf99af7b1109a89b74f3ca9d29d57aa51df1c#diff-8d9ab8d854eca0de36f86df2eff4b1473d1c6500f29d5e54510c9b5d613d4e1fL7) may lead to the following error:

> Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/pako.es5.js' is not defined by "exports" in package dir\node_modules\pizzip\node_modules\pako\package.json

Reverting the change seems to fix the issue but I am not certain if it's the right approach.

**Comment by edi9999** [comment]
Hello,

Which tool are you using that outputs this kind of error ?

**Comment by velislavgerov** [comment]
> 
> Hello, Which tool are you using that outputs this kind of error ?

I am using Node.js v12.18.4 and npm 6.15.4. I initialize a new project and install pizzip. When I try to import the module with require the exception is thrown.

Below is the line to reproduce:
`const PizZip = require('pizzip')`

**Comment by edi9999** [comment]
I have just tried and I don't get this behavior by simply running 

```
const PizZip = require('pizzip')
```

in pure node.

Are you using webpack/nuxt or something to bundle your files ?

**Comment by edi9999** [comment]
Maybe this is a typescript error ?

**Comment by edi9999** [comment]
This seems to be dependent on the node version that you use.

If you use node version 12.22.0, it will work.

See this stackoverflow answer that I wrote about some of the details : https://stackoverflow.com/a/68729949/1993501

**Comment by VitaliyBogdanov** [comment]
Hi.
I have same problem but i cant change node version "for organizational reasons". 
But i see MR #19  which solves this problem. @edi9999 can you merge it?

**Comment by edi9999** [comment]
Hello, the problem with that merge request is that it will fail the build for webpack users in general, so I'm not willing to merge it.

You can also install version 3.0.6 of pizzip to not have this issue.

**Comment by Antonimo19** [comment]
In what file and where do you add the `const PizZip = require('pizzip')` line?

**Comment by denislutz** [comment]
My constellation:
node v16.14.2 (npm v6.14.8)
It works with pizzip 3.0.6

**Comment by smff** [comment]
steel  Can't resolve 'pako/dist/pako.es5.js'
