### ISSUE TITLE
Types introduced in 3.1.2 are incorrect

### ISSUE THREAD

**Issue by ldiqual** [open-xml-templating/pizzip#24]
Most notably:
 - `new PizZip(contents)` exists in @types/pizzip but not in packaged types
 - `PizZip.load(contents)` exists in packaged types but doesn't exist in the code. Need to use `zipInstance.load(contents)`
 - `file.async('nodebuffer')` exists in packaged types but doesn't exist in the code

The following types were working great until now: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pizzip/index.d.ts

**Comment by Guergeiro** [comment]
Same issue here... Now my project doesn't build, not even with the types from `DefinetelyTyped`.

**Comment by Timebutt** [comment]
Seeing the same thing here!

**Comment by edi9999** [comment]
I have just released version 3.1.3, it should be better now.

**Comment by ldiqual** [comment]
@edi9999 Thank you Edgar, these types work great.
