### ISSUE TITLE
Inconsistent Behavior of instanceof ArrayBuffer Across Multiple Threads/Web Workers in Browsers

### ISSUE THREAD

**Issue by omnisip** [open-xml-templating/pizzip#36]
**Title:** Inconsistent Behavior of `instanceof ArrayBuffer` Across Multiple Threads/Web Workers in Browsers

**Product:** Pizzip JavaScript Library

**Version:** 3.1.6

**Environment:** Browsers with support for Web Workers

**Description:**
The Pizzip library is currently utilizing the `instanceof ArrayBuffer` check to determine if the input is an instance of `ArrayBuffer`. This approach, however, is not reliable across multiple threads or web workers in a browser environment. The `instanceof` operator checks the prototype chain for the presence of `ArrayBuffer.prototype`, which can lead to inconsistent results when contexts like web workers are involved, where each worker has its own global scope and thus its own `ArrayBuffer` constructor.

This created an issue for me when I used fetch() to capture an asset from a website.  I tried to use the array buffer to pass to PizZip and got this.

![image](https://github.com/open-xml-templating/pizzip/assets/305190/c80e49d0-1b08-4bdd-bf74-6b13196dc7cf)

**Steps to Reproduce:**
1. Initialize Pizzip in a browser environment that supports web workers.
2. Pass an `ArrayBuffer` object created in a different thread or web worker to Pizzip.
3. Observe the failure of the `instanceof ArrayBuffer` check, leading to unexpected behavior or errors.

**Expected Result:**
The `instanceof ArrayBuffer` check should consistently identify `ArrayBuffer` instances regardless of the thread or web worker context they are created in.

**Actual Result:**
The `instanceof ArrayBuffer` check fails when an `ArrayBuffer` is passed from a different thread or web worker, causing Pizzip to not recognize the input as a valid `ArrayBuffer`.

**Impact:**
This issue can lead to significant problems in applications that rely on Pizzip for handling binary data within web workers, potentially causing incorrect processing of `ArrayBuffer` data or even application crashes.

**Workaround:**
A potential workaround is to use `Object.prototype.toString.call(input) === '[object ArrayBuffer]'` as a more reliable check for `ArrayBuffer` instances.

**Suggested Fix:**
It is recommended to replace the `instanceof ArrayBuffer` check with a more robust method that does not rely on the prototype chain, such as the aforementioned `Object.prototype.toString.call()` method, or by checking the `input.constructor.name` property when appropriate.

**Comment by edi9999** [comment]
Interesting, indeed it would make more sense to use the `Object.prototype.toString.call(input) === '[object ArrayBuffer]'` condition

**Comment by edi9999** [comment]
It should be fixed in the version I've just released, version 3.1.7

I hope it will work for you !

**Comment by omnisip** [comment]
It works! Thanks Edgar!
