### ISSUE TITLE
Unsupported format

### ISSUE THREAD

**Issue by janswist** [open-xml-templating/pizzip#6]
It's used with .docx files in Docxtemplater so I'm confused by this error. Or it's really not supposed to add .docx files to zip?

```
Uncaught Error: The data of '0.docx' is in an unsupported format !
    at PizZip.fileAdd (object.js?73e2:556)
    at PizZip.file (object.js?73e2:150)
```

**Comment by edi9999** [comment]
I don't see the code that you wrote, but probably you're not passing the object as a nodejs buffer, but are doing something else.
